FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src
COPY ["LogisticsManagementSystem/LogisticsManagementSystem.csproj", "LogisticsManagementSystem/"]
RUN dotnet restore "LogisticsManagementSystem/LogisticsManagementSystem.csproj"
COPY . .
WORKDIR "/src/LogisticsManagementSystem"
RUN dotnet publish -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS final
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "LogisticsManagementSystem.dll"]